In [25]:
# Question 1 - Arrays

import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    
    
    
    return (numpy.array(arr[::-1], float))
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5
[5. 4. 3. 2. 1.]


In [23]:
# Question 2 - Transpose and Flatten

import numpy
m ,n= map(int,input().split())
arr = numpy.array([input().strip().split() for _ in range(m)], int)
print(arr.transpose())
print(arr.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [24]:
# Question 3 - Concatenate

import numpy
n,m,p = map(int, input().split())

arrA = numpy.array([input().split() for _ in range(n)], int)
arrB = numpy.array([input().split() for _ in range(m)], int)

print(numpy.concatenate((arrA,arrB), axis= 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [37]:
# Question 4 - Re.split()
import numpy as np

n = tuple(map(int, input().split()))
print(np.zeros(n, dtype=int))
print(np.ones(n, dtype=int))




3
[0 0 0]
[1 1 1]


In [44]:
# Question 5 - Eye and Identity

n,m = map(int,input().split())
numpy.set_printoptions(legacy='1.13')
print(numpy.eye(n,m))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [3]:
# Question 6 - Array Mathematics
import numpy

n,m = map(int, input().split())

a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.add(a,b))
print(numpy.subtract(a,b))
print(numpy.multiply(a,b))
print(numpy.floor_divide(a,b))
print(numpy.mod(a,b))
print(numpy.power(a,b))



1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [7]:
# Question 7 - Floor, Ceil and Rint

import numpy

A = numpy.array([float(x) for x in input().split()],float)
numpy.set_printoptions(legacy='1.13')
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [11]:
# Question 8 - Sum and Prod

import numpy

n,m = map(int, input().split())

a = numpy.array([input().split() for _ in range(n)], int)


sum_b = numpy.sum(a, axis = 0)
print(numpy.prod(sum_b))

2 2
1 2
3 4
24


In [12]:
# Question 9 - Min and Max

import numpy

n,m = map(int, input().split())

a = numpy.array([input().split() for _ in range(n)], int)

print(numpy.mean(a, axis = 1))
print(numpy.var(a, axis = 0))
std = numpy.std(a)
print(numpy.around(std, 11))

4 2
2 5
3 7
1 3
4 0
3


In [13]:
# Question 10 - Mean, Var and Std

n,m = map(int, input().split())

a = numpy.array([input().split() for _ in range(n)], int)

print(numpy.mean(a, axis = 1))
print(numpy.var(a, axis = 0))
print(numpy.std(a, axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [16]:
# Question 11 - Dot and Cross

n = int(input())

a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a,b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [20]:
# Question 12 - Inner and Outer

a = numpy.array(input().split(),int)
b = numpy.array(input().split(),int)

print(numpy.inner(a,b))
print(numpy.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]


In [22]:
# Question 13 - Polynomials

a = numpy.array(input().split(),float)
p = int(input())

print(numpy.polyval(a,p))

1.1 2 3
0
3.0


In [25]:
# Question 14 - Linear Algebra

n = int(input())
a = numpy.array([input().split() for _ in range(n)], float)
numpy.set_printoptions(legacy='1.13')
print(numpy.linalg.det(a))

2
1.1 1.1
1.1 1.2
0.11
